name: Update PlantUML
on:
  schedule:
    - cron: "0 0 10 * *"
  workflow_dispatch:

jobs:
  bump_plantuml:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: plantuml
        # using plantuml-server because plantuml for some reason returns empty list of releases
        name: PlantUML latest release
        run: |
          echo "tag=$(curl -s https://api.github.com/repos/plantuml/plantuml-server/releases/latest | grep tag_name | sed 's/.*"tag_name": "v\(.*\)",/\1/')" >> $GITHUB_OUTPUT

      - name: "Get latest tag"
        id: current
        run: |
          echo "tag=$(git ls-remote --tags --refs --sort="v:refname" origin | tail -n1 | sed 's/.*\///')" >> $GITHUB_OUTPUT

      - name: Bump docker version
        if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
        run: |
          sed -i "s#hokorobi/plantuml:.*#hokorobi/plantuml:${{ steps.plantuml.outputs.tag }}\"#" action.yml

      - name: Push Local Changes
        if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump PlantUML to ${{ steps.plantuml.outputs.tag }}"
          tagging_message: ${{ steps.plantuml.outputs.tag }}

      - name: Set up QEMU
        if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.plantuml.outputs.tag != steps.current.outputs.tag }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hokorobi/plantuml:latest, hokorobi/plantuml:${{ steps.plantuml.outputs.tag }}
          build-args: |
            PLANTUML_VERSION=${{ steps.plantuml.outputs.tag }}
